name: Auto Format with Ruff

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  format:
    name: "Format with Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto format with ruff"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
